version: '2'

services:
  redis:
    image: redis
    expose:
      - 6379

  writer:
    build:
      context: ./
      dockerfile: Dockerfile-writer
    env_file: .env
    links: 
      - redis

  reader:
    build:
      context: ./
      dockerfile: Dockerfile-reader
    env_file: .env
    links: 
      - redis
    ports: 
      - "5000:5000"

  website:
    build:
      context: website
    ports: 
      - "8080:80"
